logging:
  level:
    org.springframework: ERROR
    com.inventory: INFO 

spring:
  application:
    name: inventory-service
    
  profiles:
  - '@active_profile@'  
 
#  datasource:
#    url: jdbc:postgresql://192.168.99.100:5432/asset_management_db
#    username: asset_manager
#    password: secret   
# 
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#       dialect: org.hibernate.dialect.PostgreSQLDialect
      
  


    

      
     
