server:
  port: 9090

logging:
  level:
    org.springframework: ERROR
    com.inventory: INFO 

spring:
  application:
    name: inventory-service
    
  profiles:
    active:
    - '@active_profile@'  
      
  


    

      
     
